[phases.build]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --preload"

[variables]
PYTHONUNBUFFERED = "1"
FLASK_ENV = "production"
