services:
  - type: web
    name: ocr-flask-app
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.16
    plan: free
    region: oregon
    autoDeploy: true
