services:
  - type: web
    name: ocr-flask-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT --timeout 120"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.9.16"
    plan: free
    region: oregon
    autoDeploy: true